repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
    args: ["--ignore", "CONTRIBUTING.md"]
- repo: https://github.com/trussworks/pre-commit-hooks
  rev: v1.1.1
  hooks:
    - id: mdspell
      files: '.*/.*.md'
    - id: spelling-sort
