title: Introduction to digital work
description: Introduction to digital work (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/digital-work-lecture

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/digital-work-lab/digital-work-lecture'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'


logo: "/assets/images/IDW-logo.png"