title: Introduction to digital work
description: Introduction to digital work (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/digital-work-lecture

gh_edit_link: true
gh_edit_link_text: 'Help improve this page'
gh_edit_repository: 'https://github.com/digital-work-lab/digital-work-lecture'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

mermaid:
  version: "11.4.0"

callouts:
  warning:
    title: Warning
    color: red
  deliverable:
    title: Deliverable
    color: yellow
  info:
    color: yellow
  feedback:
    title: Student feedback
    color: blue
  objective:
    title: Learning objective
    color: blue
  see_also:
    title: See also
    color: green

logo: "/assets/images/IDW-logo.png"

aux_links:
  "Repository":
    - "https://github.com/digital-work-lab/digital-work-lecture"
  "Improvement":
    - "https://github.com/digital-work-lab/digital-work-lecture/issues"
